### ISSUE TITLE
Update Walker for WP 4.5

### ISSUE THREAD

**Issue by grappler** [helgatheviking/Nav-Menu-Roles#19] opened 2016-05-04 11:56 UTC
In WP 4.5 the menu items looks like this because the class ` wp-clearfix` is missing.

![image](https://cloud.githubusercontent.com/assets/1785641/15013419/c3f9ea0e-11ff-11e6-9bfd-c564f72e66db.png)

**Comment by lkraav** [comment] 2016-05-04 11:59
This is real, I'm seeing the same thing.

**Comment by helgatheviking** [comment] 2016-05-04 13:45
Duplicate of #17

**Closed by helgatheviking** 2016-05-04 13:45 UTC

**Comment by helgatheviking** [comment] 2016-05-04 14:04
Could you both test the [wp-4.5-compat](https://github.com/helgatheviking/Nav-Menu-Roles/tree/wp-4.5-compat) branch?

**Comment by helgatheviking** [comment] 2016-05-04 14:26
Fixed by 344988bc7d15120cbcdf0a6ce87c90df9f7e7b31
